export enum PlayerState {
    STATE_IDLE = "IDLE",
    STATE_PREPARED = "PREPARED",
    STATE_STARTED = "STARTED",
    STATE_PAUSED = "PAUSED",
    STATE_STOPPED = "STOPPED",
    STATE_COMPLETED = "COMPLETED",
    STATE_ERROR = "ERROR",

    STATE_BUFFER_START = "BUFFER_START",
    STATE_BUFFER_END = "BUFFER_END",
    STATE_BUFFER_UPDATE = "BUFFER_UPDATE",
}