/**
 * AspectRatio mode define.
 *
 * Author: Seagazer
 * Date: 2022/09/14
 */
export enum AspectRatio {
    /**
     * Auto
     */
    AUTO,

    /**
     * W16:9
     */
    W_16_9,

    /**
     * W4:3
     */
    W_4_3,

    /**
     * W21:9
     */
    W_21_9,

    /**
     * Stretch to fill view size
     */
    STRETCH,

    /**
     * Keep video aspectRatio and fill view size
     */
    FILL,
}